kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ic
  namespace: nginx
subjects:
- kind: ServiceAccount
  name: ic
roleRef:
  kind: Role
  name: ic
  apiGroup: rbac.authorization.k8s.io